checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_code_sniffer: true
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    external_code_coverage:
        timeout: 1200
        runs: 3
filter:
    excluded_paths:
        - 'tests/*'
