language: php
php:
  - 5.3
  - 5.4
  - 5.5

branches:
  except:
    - share

env:
    - DB=sqlite

before_install:
  - ./tests/install_dependencies.sh
  - tests/setup_owncloud.sh


script:
  - sh -c "if [ '$DB' = 'sqlite' ]; then ant test; fi"
  - phpunit --configuration tests/phpunit.xml --testsuite unit-tests
