language: php
php:
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - CORE_BRANCH=master
  matrix:
    - DB=sqlite

before_install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh ocusagecharts $CORE_BRANCH $DB
  - cd ../core
  - php occ app:enable ocusagecharts

script:
  # Test lint
  - cd apps/ocusagecharts
  - sh -c "if [ '$DB' = 'sqlite' ]; then ant test; fi"

  # Run phpunit tests
  - cd tests
  - phpunit --configuration phpunit.xml --coverage-clover=coverage.clover

  # Create coverage report
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

# try in future
#after_success:
#  - coveralls
