- name: Check if owncloud database exists
  mysql_db: name=owncloud state=present
  sudo: yes

- name: Copy owncloud sql to tmp
  copy: src=owncloud.sql dest=/tmp
  sudo: yes

- name: Import owncloud sql into database owncloud
  mysql_db: name=owncloud state=import target=/tmp/owncloud.sql
  sudo: yes

- name: Create owncloud database user
  mysql_user: user=vagrant host=localhost password=vagrant login_user=root login_password={{ mysql_root_password }} priv=owncloud.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER state=present
  sudo: yes