- name: Configure webservers
  hosts: webservers
  remote_user: vagrant
  sudo: yes
  roles:
    - web

- name: Configure database servers
  hosts: dbservers
  remote_user: vagrant
  sudo: yes
  roles: 
    - db

- name: Configure owncloud
  hosts: webservers
  remote_user: vagrant
  roles:
    - owncloud
    - composer